name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]

    env:
      DO_COVERALLS: 20.9.0

    steps:
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout from Git
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage report
      run: |-
        if [ "${{ matrix.node-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm run coveralls
        else
          true
        fi
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Run tests and coverage report
      run: |-
        if [ ! "${{ matrix.node-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm test
        else
          true
        fi
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

  notify_slack:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Notify Slack
      uses: homoluctus/slatify@master
      with:
        type: ${{ needs.test.result }}
        job_name: '${{ github.repository }} - Tests'
        channel: '#dhl-ecommerce-solutions'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'
